apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::975722656191:role/eksctl-kubernetes-github-actions-NodeInstanceRole-87FV62IOBVHW
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::975722656191:user/kubernetes-github-actions
      username: kubernetes-github-actions
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::975722656191:role/eksctl-kubernetes-github-actions-NodeInstanceRole-87FV62IOBVHW\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::975722656191:user/kubernetes-github-actions\n  username: kubernetes-github-actions\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-07-23T03:31:36Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"999","uid":"eae1d17a-646e-405e-bc63-e4b85e575054"}}
  creationTimestamp: "2023-07-23T03:31:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2532"
  uid: eae1d17a-646e-405e-bc63-e4b85e575054
