apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3lNekF6TWpVME1sb1hEVE16TURjeU1EQXpNalUwTWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTzdoClhNOUd5NVpzVjhzNWI3UGJiYnlObHNWeVZVRmFiVWhyOHhmVnBrTk53NE8xZUpwWnpkUnREdER2bnByYXVUanEKajhIRHhkZDkrSEpEY2xqbGNjQnJVVDFiaStiU25iNHNkNmhRSlU1Y3NBaHZaRSt4N1BNbEo4UHN3N1R5YkJCNQppMDNGUUQ0QzRmNVQwUXNoaVJDeFQrVFBtK2J3QVQ0eTN2aWVha3h4d1JxT2V6bVcvUitjenJscUJXY3dCbkRLClBvQndjUXZXT0pSajhiS1kxN1ErdzZTTFVSVmZRNU4zYUdSekQrYWhzdzlaMmMzMWFnVVpMZlVZNWNURkx5MVQKVEtHTlVGVXN1YlZZQ3IwRDJSZSt4SlE4a083V3hPa1U5akV6bHZrL1lyTGhiTHdSUDBHSGxCRXJld1dqTnVIWQo2Rm5ZS2RUSGFXYzErVkJJYkEwQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZHcVg1d2tjR2tLZGp2WG9nNE0vdE5ub05velVNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTkZaWEw3L1hMaUxGTTcvV1NUdApyNHRFR3BNTENzV293TnIxTXg5MjR5aTZFZ3krcmp4K1hNMGdjOVN1T0xTcUpjYk9mbWgxb2VYVG13OTVIK29sCkpPa1g5TnVyc0dBTUdoQlo2a1VvWWY0R3VaM2x0MURuUHhlU203dWFhbzRidVV2UnpEV0E4by9EdUExK1N1SjQKeHo1Yk1oVlRMMzBENHJFbDhkd1J2ZHNYTldRTElob2pXeDZodDhOVjk3dHpCak9hTGZhQ0xvSmlNekNhYWJ5VQpRZXVPemRMbElYWEszWkU1am0vWXlxbHlnbTI1d1oxbW9RNkIvU2lZdi8vNTkycTQvRm81bVcrdUlub1NGUGtICjg0TngwQTZYTlJPUVVLZTRNL2hMa3J5QVY2OC9IMGxZdnJXOXRuWnhOUGpwMk5lWEMzSGJpY3pGODhvZ3lHUkkKbS9zPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://895AF09D36791DE1C96BCABF146E3E66.gr7.eu-west-3.eks.amazonaws.com
    name: kubernetes-github-actions.eu-west-3.eksctl.io
contexts:
  - context:
      cluster: kubernetes-github-actions.eu-west-3.eksctl.io
      user: kubernetes-github-actions@kubernetes-github-actions.eu-west-3.eksctl.io
    name: kubernetes-github-actions@kubernetes-github-actions.eu-west-3.eksctl.io
current-context: kubernetes-github-actions@kubernetes-github-actions.eu-west-3.eksctl.io
kind: Config
preferences: {}
users:
  - name: kubernetes-github-actions@kubernetes-github-actions.eu-west-3.eksctl.io
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - eks
          - get-token
          - --output
          - json
          - --cluster-name
          - kubernetes-github-actions
          - --region
          - eu-west-3
        command: aws
        interactiveMode: IfAvailable
